# Generated by Django 3.0.7 on 2020-06-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysite', '0002_auto_20200608_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='number',
        ),
        migrations.AddField(
            model_name='query',
            name='user_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='query',
            name='vid_num',
            field=models.CharField(default='', max_length=5),
        ),
    ]
