# Generated by Django 3.0.7 on 2020-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysite', '0003_auto_20200609_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=25)),
                ('speed', models.FloatField()),
                ('timestamp', models.FloatField()),
                ('user_id', models.IntegerField()),
                ('vid_num', models.IntegerField()),
            ],
        ),
    ]
